function kview_OffsetAndGain(varargin)
% SYNTAX:
%   kview_CustomButtons(CustomPanelHandle)
%
%
% INPUT (OPTIONAL):
%   CustomPanelHandle   - Handle to the panel that will contains all the
%                         new controls.



if isempty(varargin)
    
    FigHandle = figure;
    CustomPanelHandle = uipanel(...
        'Parent',FigHandle,...
        'Units','pixels',...
        'FontSize',10,...
        'Clipping','on',...
        'Position',[5 5 540 120]);
    
else
    
    CustomPanelHandle = varargin{1};
    
end




h1 = uicontrol(...
'Parent',CustomPanelHandle,...
'FontSize',10,...
'Position',[66 92 60 20],...
'String','Offset:',...
'Style','text',...
'Tag','text1');
kview_OaG_handles.(get(h1,'Tag'))= h1;


h2 = uicontrol(...
'Parent',CustomPanelHandle,...
'BackgroundColor',[1 1 1],...
'FontSize',10,...
'Position',[129 92 80 20],...
'String','0',...
'Style','edit',...
'Tag','XOffset_val');
kview_OaG_handles.(get(h2,'Tag'))= h2;


h3 = uicontrol(...
'Parent',CustomPanelHandle,...
'FontSize',10,...
'Position',[223 92 60 20],...
'String','Gain:',...
'Style','text',...
'Tag','text2');
kview_OaG_handles.(get(h3,'Tag'))= h3;

h4 = uicontrol(...
'Parent',CustomPanelHandle,...
'BackgroundColor',[1 1 1],...
'FontSize',10,...
'Position',[287 92 80 20],...
'String','1',...
'Style','edit',...
'Tag','XGain_val');
kview_OaG_handles.(get(h4,'Tag'))= h4;

h5 = uicontrol(...
'Parent',CustomPanelHandle,...
'FontSize',10,...
'FontWeight','bold',...
'Position',[7 92 60 20],...
'String','X axis',...
'Style','text',...
'Tag','text4');
kview_OaG_handles.(get(h5,'Tag'))= h5;

h6 = uicontrol(...
'Parent',CustomPanelHandle,...
'FontSize',10,...
'Position',[66 66 60 20],...
'String','Offset:',...
'Style','text',...
'Tag','text5');
kview_OaG_handles.(get(h6,'Tag'))= h6;

h7 = uicontrol(...
'Parent',CustomPanelHandle,...
'BackgroundColor',[1 1 1],...
'FontSize',10,...
'Position',[129 66 80 20],...
'String','0',...
'Style','edit',...
'Tag','YOffset_val');
kview_OaG_handles.(get(h7,'Tag'))= h7;

h8 = uicontrol(...
'Parent',CustomPanelHandle,...
'FontSize',10,...
'Position',[223 66 60 20],...
'String','Gain:',...
'Style','text',...
'Tag','text6');
kview_OaG_handles.(get(h8,'Tag'))= h8;

h9 = uicontrol(...
'Parent',CustomPanelHandle,...
'BackgroundColor',[1 1 1],...
'FontSize',10,...
'Position',[287 66 80 20],...
'String','1',...
'Style','edit',...
'Tag','YGain_val');
kview_OaG_handles.(get(h9,'Tag'))= h9;

h10 = uicontrol(...
'Parent',CustomPanelHandle,...
'FontSize',10,...
'FontWeight','bold',...
'Position',[7 66 60 20],...
'String','Y axis',...
'Style','text',...
'Tag','text7');
kview_OaG_handles.(get(h10,'Tag'))= h10;


h11 = uicontrol(...
'Parent',CustomPanelHandle,...
'Units','pixels',...
'Callback',{@OffsetAndGain_Action,CustomPanelHandle,1},...
'FontSize',10,...
'Position',[410 65 100 40],...
'String','Plot',...
'Tag','pushbutton1');
kview_OaG_handles.(get(h11,'Tag'))= h11;


h12 = uicontrol(...
'Parent',CustomPanelHandle,...
'Units','pixels',...
'Callback',{@OffsetAndGain_Action,CustomPanelHandle,2},...
'FontSize',10,...
'Position',[410 15 100 40],...
'String','Apply',...
'Tag','pushbutton1');
kview_OaG_handles.(get(h12,'Tag'))= h12;



% Cut WIP Section

h13 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...
    'Callback',{@CutEnable,CustomPanelHandle},...
    'FontSize',10,...
    'Position',[7 36 100 20],...
    'String','Cut (WIP)',...
    'Style','checkbox',...
    'Value',0,...
    'Tag','cut_checkbox');
kview_OaG_handles.(get(h13,'Tag'))= h13;


h14 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...    
    'FontSize',10,...
    'Position',[100 36 60 20],...
    'String','Before',...
    'Style','checkbox',...
    'Value',0,...
    'Tag','before_checkbox',...
    'Enable','off');
kview_OaG_handles.(get(h14,'Tag'))= h14;


h15 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...    
    'FontSize',10,...
    'Position',[100 10 60 20],...
    'String','After',...
    'Style','checkbox',...
    'Value',0,...
    'Tag','after_checkbox',...
    'Enable','off');
kview_OaG_handles.(get(h15,'Tag'))= h15;



h16 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...    
    'FontSize',10,...  
    'Position',[300 10 80 20],...
    'String','Get by graph',...
    'Callback',{@CutGetByGraph,CustomPanelHandle},...
    'Enable','off',...
    'Tag','getbygraphafter_pushbutton');
kview_OaG_handles.(get(h16,'Tag'))= h16;


h17 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...    
    'FontSize',10,...  
    'Position',[200 10 80 20],...
    'String','Get by graph',...
    'Callback',{@CutGetByGraph,CustomPanelHandle},...
    'Enable','off',...
    'Style','Edit',...
    'String','0',...
    'Tag','cutvalueafter_edit');
kview_OaG_handles.(get(h17,'Tag'))= h17;


h16 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...    
    'FontSize',10,...  
    'Position',[300 36 80 20],...
    'String','Get by graph',...
    'Callback',{@CutGetByGraph,CustomPanelHandle},...
    'Enable','off',...
    'Tag','getbygraphbefore_pushbutton');
kview_OaG_handles.(get(h16,'Tag'))= h16;


h17 = uicontrol(...
    'Parent',CustomPanelHandle,...
    'Units','pixels',...    
    'FontSize',10,...  
    'Position',[200 36 80 20],...
    'String','Get by graph',...
    'Callback',{@CutGetByGraph,CustomPanelHandle},...
    'Enable','off',...
    'Style','Edit',...
    'String','0',...
    'Tag','cutvaluebefore_edit');
kview_OaG_handles.(get(h17,'Tag'))= h17;



setappdata(CustomPanelHandle,'kview_OaG_handles',kview_OaG_handles);




function CutGetByGraph(hObject,~,CustomPanelHandle)





function CutEnable(hObject,~,CustomPanelHandle)

% get data:
kview_OaG_handles = getappdata(CustomPanelHandle,'kview_OaG_handles');
value = get(kview_OaG_handles.cut_checkbox,'Value');

if value == 0
    set(kview_OaG_handles.before_checkbox,'Enable','off');
    set(kview_OaG_handles.after_checkbox,'Enable','off');
    set(kview_OaG_handles.getbygraphbefore_pushbutton,'Enable','off');
    set(kview_OaG_handles.cutvaluebefore_edit,'Enable','off');
    set(kview_OaG_handles.getbygraphafter_pushbutton,'Enable','off');
    set(kview_OaG_handles.cutvalueafter_edit,'Enable','off');
else
    set(kview_OaG_handles.before_checkbox,'Enable','on');
    set(kview_OaG_handles.after_checkbox,'Enable','on');
%     set(kview_OaG_handles.getbygraphbefore_pushbutton,'Enable','on');
    set(kview_OaG_handles.cutvaluebefore_edit,'Enable','on');
%     set(kview_OaG_handles.getbygraphafter_pushbutton,'Enable','on');
    set(kview_OaG_handles.cutvalueafter_edit,'Enable','on');
end




function OffsetAndGain_Action(hObject,~,CustomPanelHandle,num)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


%% ----------------------------------------------------- Initialization ---

% Get data from the OffsetAndGain_export GUI:
kviewGUI_handles = guidata(hObject);
kview_OaG_handles = getappdata(CustomPanelHandle,'kview_OaG_handles');
XOffset = str2double(get(kview_OaG_handles.XOffset_val,'String'));
XGain = str2double(get(kview_OaG_handles.XGain_val,'String'));
YOffset = str2double(get(kview_OaG_handles.YOffset_val,'String'));
YGain = str2double(get(kview_OaG_handles.YGain_val,'String'));


% Check Gain and Offset values
if isempty(XOffset); XOffset = 0; elseif isnan(XOffset); display('Error: the X Offset value you inserted is not recognized as a number.'); return; end
if isempty(XGain); XGain = 1; elseif isnan(XGain); display('Error: the X Gain value you inserted is not recognized as a number.'); return; end
if isempty(YOffset); YOffset = 0; elseif isnan(YOffset); display('Error: the Y Offset value you inserted is not recognized as a number.'); return; end
if isempty(YGain); YGain = 1; elseif isnan(YGain); display('Error: the Y Gain value you inserted is not recognized as a number.'); return; end


% Get data from the main kview GUI:
contents_listbox1 = cellstr(get(kviewGUI_handles.listbox1,'String'));
contents_listbox2 = cellstr(get(kviewGUI_handles.listbox2,'String'));
contents_listbox3 = cellstr(get(kviewGUI_handles.listbox3,'String'));
value_listbox1 = get(kviewGUI_handles.listbox1,'Value');
value_listbox2 = get(kviewGUI_handles.listbox2,'Value');
value_listbox3 = get(kviewGUI_handles.listbox3,'Value');
DatasetsStruct = getappdata(kviewGUI_handles.main_GUI,'DatasetsStruct');
XAxisVarName = getappdata(kviewGUI_handles.main_GUI,'XAxisVarName');
XAxisSubsysName = getappdata(kviewGUI_handles.main_GUI,'XAxisSubsysName');



%% ----------------------------------------------------------- Cut Data ---

CutEnabled = get(kview_OaG_handles.cut_checkbox,'Value');

if CutEnabled
    CutBefore = get(kview_OaG_handles.before_checkbox,'Value');
    CutAfter = get(kview_OaG_handles.after_checkbox,'Value');
    CutValueBefore = str2double(get(kview_OaG_handles.cutvaluebefore_edit,'String'));
    CutValueAfter = str2double(get(kview_OaG_handles.cutvalueafter_edit,'String'));
    xAxisDefined = ~isempty(XAxisSubsysName);
    
    for ii = value_listbox1   
        if xAxisDefined
            CutPosBefore = find(DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data>CutValueBefore,1,'first');
            CutPosAfter = find(DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data>CutValueAfter,1,'first');
        else
            CutPosBefore = CutValueBefore;
            CutPosAfter = CutValueAfter;
        end
        
        if isempty(CutPosBefore) || ~CutBefore
            CutPosBefore = 1;           
        end  
        
        if isempty(CutPosAfter) || ~CutAfter
            if xAxisDefined
                CutPosAfter = length(DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data);          
            else
                CutPosAfter = length(DatasetsStruct.(contents_listbox1{ii}).(contents_listbox2{1}).(contents_listbox3{1}).data);
            end
        end  
        
        if xAxisDefined
            DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data =...
                DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data(CutPosBefore:CutPosAfter);
        end

    
        for jj = value_listbox2
            for kk = value_listbox3    
                    
                DatasetsStruct.(contents_listbox1{ii}).(contents_listbox2{jj}).(contents_listbox3{kk}).data =...
                    DatasetsStruct.(contents_listbox1{ii}).(contents_listbox2{jj}).(contents_listbox3{kk}).data(CutPosBefore:CutPosAfter);              
                    
            end
        end
        
    end

end




%% ------------------------------------------------------ Offset & Gain ---

% Apply Gain and Offset to X Axis (if exist)
for ii = value_listbox1
    
    
    if isfield(DatasetsStruct.(contents_listbox1{ii}),XAxisSubsysName)
        if ~isfield(DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName),XAxisVarName)
            display(['ERROR: the variable ' XAxisSubsysName '.' XAxisVarName ' selected as X axis is not a field of ' contents_listbox1{ii}]);
            display('No offset or gain was applied to any variable.');
            return
        end
    else
        display(['ERROR: the subsystem ' XAxisSubsysName ' needed for the X axis is not a field of ' contents_listbox1{ii}]);
        display('No offset or gain was applied to any variable.');
        return
    end
     
    
    DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data =...
        (DatasetsStruct.(contents_listbox1{ii}).(XAxisSubsysName).(XAxisVarName).data...
        + XOffset) * XGain;
            
end

% Apply Gain and Offset to Y Axis
for ii = value_listbox1
    for jj = value_listbox2
        for kk = value_listbox3

            DatasetsStruct.(contents_listbox1{ii}).(contents_listbox2{jj}).(contents_listbox3{kk}).data =...
                (DatasetsStruct.(contents_listbox1{ii}).(contents_listbox2{jj}).(contents_listbox3{kk}).data...
                + YOffset) * YGain;

        end
    end
end


%% ------------------------------------------------------ Show and Save ---

% Show or store modified values
if num == 1
    kviewPlot(kviewGUI_handles.main_GUI,[],'NewFigure',DatasetsStruct);
else
    setappdata(kviewGUI_handles.main_GUI,'DatasetsStruct',DatasetsStruct);
end


